//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nasibe.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewMain
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<double> ProductCount { get; set; }
        public string CatalogValue { get; set; }
        public Nullable<int> ProductUnitPrice { get; set; }
        public string ProductData { get; set; }
        public string ProductDescription { get; set; }
        public bool ProductPopularSupport { get; set; }
        public string ByPpl { get; set; }
        public string ProductPrice { get; set; }
        public Nullable<int> ProductUnitCount { get; set; }
    }
}
